### ISSUE TITLE
OrangeIRC Core

### ISSUE THREAD

**Issue by vibou** [ahyattdev/OrangeIRC#6]
Would it be possible to have OrangeIRC Core on Cocoapod ? that would be awesome !

**Comment by ahyattdev** [comment]
Yes. In order to do this I need to move the project over from Carthage (it has a dependency, CocoaAsyncSocket), so it will take some time.

**Comment by ahyattdev** [comment]
See if it works for you when you add this to your `Podfile`:

`pod 'OrangeIRC', :git => 'https://github.com/ahyattdev/OrangeIRC.git'`

And then import with `import OrangeIRCCore`. 

The documentation isn't good as of now, but `Server.connect` should get you started.

**Comment by vibou** [comment]
Thanks :)

**Comment by vibou** [comment]
I really think OrangeIRCCore should be a different git repo. Don't you want to create another git depo with only OrangeIRCCore and use it in Podfile for OrangeIRC iOS? 

However it does not really matter since in podspec I ignore ios bundles...

**Comment by vibou** [comment]
May be you could reject my pull request since you did almost everything I did in my fork. However that could be great to fix the typo issues.

**Comment by ahyattdev** [comment]
archiving repository
